---
title: "MitchDataSet"
output: html_document
---

```{r}
library(tidyverse)
library(polite)
library(rvest)
library(stringr)
```

```{r}

robotstxt::paths_allowed("https://en.wikipedia.org/wiki/Wikipedia:WikiProject_National_Basketball_Association/National_Basketball_Association_team_abbreviations")
```

```{r}
# scrape list of team abbreviations from wikipedia and clean up list of team abbreviations
team_abbv_wiki <- read_html("https://en.wikipedia.org/wiki/Wikipedia:WikiProject_National_Basketball_Association/National_Basketball_Association_team_abbreviations")

team_abbv_temp <- html_nodes(team_abbv_wiki, "td:nth-child(1)")

team_abbv <- html_text(team_abbv_temp)
```

```{r}
# cleaning up abbreviation data
for (i in seq_along(team_abbv)) {
  team_abbv[i] <- str_replace(team_abbv[i], "^(.)(.)(.).*$", "\\1\\2\\3")
  team_abbv[i] <- str_remove(team_abbv[i], "\n")
}

# accounting for errors made by wikipedia site
team_abbv[3] = "BRK"
team_abbv[4] = "CHO"
team_abbv[24] = "PHO"
team_abbv
```

```{r}
# function to scrape basketball data
get_text_from_page <- function(page, css_selector) {
  page |> 
    html_nodes(css_selector) |> 
    html_text()
}

# function to turn basketball data into a tibble
basketball_tibble <- function(team, year = 2025) {
  url = str_c("https://www.basketball-reference.com/teams/", team, "/", year, ".html")
  session <- bow(url, force = T)
  page <- scrape(session)
  team_record <- get_text_from_page(page, ".prevnext+ p")
  points_per_g <- get_text_from_page(page, "p:nth-child(6)")
  ratings <- get_text_from_page(page, "p:nth-child(8)")
  tibble(team = team, team_record = team_record, points_per_g = points_per_g, ratings = ratings)
}

team_stats_temp <- map2(team_abbv, 2025, basketball_tibble) # creates a list of one-row tibbles for each team
team_stats <- list_rbind(team_stats_temp) # binds the tibbles together
```

```{r}
# cleaning up our tibble
team_stats <- team_stats |>
  mutate(team_record = str_extract(team_record, "\\d\\d-\\d\\d"), # extracts the xx-xx numbers from the data
         wins = parse_number(str_extract(team_record, "^\\d\\d")), # number of wins during the season 
         losses = parse_number(str_extract(team_record, "\\d\\d$")), # number of losses
         points_per_g = str_remove_all(points_per_g, " "),
         points_per_g = str_remove_all(points_per_g, "\n"), # gets rid of enters and spaces
         opp_points_per_g = str_extract(points_per_g, "OppPTS/G:\\d\\d\\d\\.\\d"),
         points_per_g = parse_number(str_extract(points_per_g, "\\d\\d\\d\\.\\d")), # points per game scored by the team
         opp_points_per_g = parse_number(str_extract(opp_points_per_g, "\\d\\d\\d\\.\\d")), # points per game scored by any given opponent team
         ratings = str_remove_all(ratings, " "),
         ratings = str_remove_all(ratings, "\n"), # gets rid of enters and spaces
         off_rating = parse_number(str_extract(ratings, "\\d\\d\\d\\.\\d")), # offensive rating
         def_rating = str_extract(ratings, "DefRtg:\\d\\d\\d\\.\\d"),
         def_rating = parse_number(str_remove(def_rating, "DefRtg:")), # defensive rating
         net_rating = off_rating - def_rating) |> # offensive rating - defensive rating
  select(-team_record, -ratings) # getting rid of placeholder variables
```

```{r}
# saving data set as csv
write_csv(team_stats, "~/sds264proj/team_stats.csv")
```